### ISSUE TITLE
You should add alignSelf: 'stretch' styles

### ISSUE THREAD

**Issue by melihmucuk** [halilb/react-native-textinput-effects#6] opened 2016-08-22 08:30 UTC
Thanks for awesome component! I think you should add `alignSelf: 'stretch'` to all examples.

```
<Fumi
    style={{alignSelf: 'stretch'}}
    label={'Course Name'}
    iconClass={FontAwesomeIcon}
    iconName={'university'}
    iconColor={'#f95a25'}
/>
```

code samples and ss for without `stretch`:

```
<View style={{flex: 1, alignSelf: 'stretch', justifyContent: 'center', alignItems:'center', backgroundColor: 'red'}}>
          <Text style={{color: 'white', fontSize: 20, fontWeight: 'bold'}}>
            Test
          </Text>
          <Fumi
            label={'Course Name'}
            iconClass={FontAwesomeIcon}
            iconName={'university'}
            iconColor={'#f95a25'}
            />
</View>
```

![simulator screen shot 22 aug 2016 11 32 17](https://cloud.githubusercontent.com/assets/3147488/17848432/19f181c6-685c-11e6-8561-0f722876069b.png)

with alignSelf: 'stretch' 

![simulator screen shot 22 aug 2016 11 33 01](https://cloud.githubusercontent.com/assets/3147488/17848440/35704194-685c-11e6-8b11-386dd3dccd45.png)

**Comment by halilb** [comment] 2016-11-18 19:01
Thanks for reporting @melihmucuk.

I tested the problem but couldn't reproduce. It's possible it has broken with certain react-native version. I've tested and it's working fine with react-native 0.36.1.

Closing the issue now but let me know if you still experience the problem!

**Closed by halilb** 2016-11-18 19:01 UTC
