### ISSUE TITLE
textInput Compenent from react-native does not work

### ISSUE THREAD

**Issue by Talkwondo** [halilb/react-native-textinput-effects#10] opened 2016-09-04 17:52 UTC
Hello, 
Thank for you great compenent. 
but please explain what do you think about the subject
  <Kohana
            placeholder="Email"
            placeholderTextColor="rgba(0,0,0,0.2)"
            keyboardType="email-address"
            selectionColor="#4c8af0"
            style={styles.input}
            autoFocus={true}
            autoCapitalize="none"
            autoCorrect={false}
            onChangeType={(email) => this.email = email}
            returnKeyType="next"
            onSubmitEditing={() => this._passwordRef.focus()}
            />

i got

<img width="364" alt="screen shot 2016-09-04 at 8 51 23 pm" src="https://cloud.githubusercontent.com/assets/20122139/18232877/6dae7adc-72e1-11e6-822e-f4b14381314e.png">

**Comment by halilb** [comment] 2016-11-18 19:09
Thanks for reporting @Talkwondo.

This problem might be related to importing the library. Can you check your import statement? It should look like this:

```
import {
  Kohana,
} from 'react-native-textinput-effects';
```

I'm closing the issue but let me know if the problem isn't fixed!

**Closed by halilb** 2016-11-18 19:09 UTC

**Comment by Talkwondo** [comment] 2016-11-21 20:36
Hi,
I don't think is about the importing. I already imported it. still have this issue
